CREATE TYPE CURRENCY AS ENUM ('RUB', 'USD');
CREATE TYPE WORK_TYPE AS ENUM ('PLANT', 'WATER', 'FERTILIZE', 'CULTIVATE', 'UPROOT');
CREATE TYPE CONDITION AS ENUM ('RICH', 'ACIDIC', 'HIGH');

CREATE DOMAIN UINT AS INT CONSTRAINT u256_range CHECK (
    VALUE >= 0 AND VALUE <= 4294967295
);

CREATE DOMAIN UREAL AS REAL CONSTRAINT u256_range CHECK (
    VALUE >= 0 AND VALUE <= 4294967295
    );