CREATE TABLE IF NOT EXISTS "plant_type" (
        urn UUID PRIMARY KEY NOT NULL,
        name TEXT UNIQUE NOT NULL,
        description TEXT NOT NULL,

        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);